### ISSUE TITLE
Node-Red version

### ISSUE THREAD

**Issue by hhoefling** [openWB/tools#1]
Hm. ich kann die 2.0.6 nicht finden.
Mit der 2.1.3 gibts Probleme
in den Sub-Flows taucht der folgenden Fehler auf (debug Ausgabe)

"TypeError: Cannot read property 'toFixed' of undefined"
in Node:"Senden der Flow-Daten"

Kann man das anpassen oder irgendwo die 2.0.6 herbekommen?

**Comment by benderl** [comment]
Habe schon etwas länger nicht mehr aktualisiert. Aktuell weiß ich nicht, ob sich da etwas geändert hat. Ich muss den Simulator für 2.0 jetzt noch aktualisieren, da sehe ich mir den 1.9er auch mit an.

**Comment by benderl** [comment]
Es hat eine Initialisierung gefehlt. Probier mal den aktualisierten Flow.

**Comment by hhoefling** [comment]
Ja, Danke.
Nun geht's
